#!/bin/sh

# Generate the C++ firmware release identifier from the current Git state.

set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repository_root=$(git -C "$script_dir" rev-parse --show-toplevel)
output_file="$script_dir/firmware_release.h"

# An exact release tag produces only that tag (for example, v3.0.1).
# Otherwise Git produces the nearest tag, commit distance, and abbreviated
# commit ID (for example, v3.0.1-4-g1a2b3c4).  A modified tree adds -dirty.
release=$(
    git -C "$repository_root" describe \
        --tags \
        --always \
        --dirty \
        --match 'v[0-9]*'
)

# Git reference names cannot contain a backslash, but escape both characters
# that could affect a C++ string literal for defensive completeness.
escaped_release=$(printf '%s' "$release" | sed 's/[\\"]/\\&/g')

temporary_file="${output_file}.tmp.$$"
trap 'rm -f "$temporary_file"' EXIT HUP INT TERM

{
    printf '%s\n' \
        '// Generated by generate-firmware-release.sh; do not edit.' \
        '#pragma once' \
        '' \
        "constexpr const char *FIRMWARE_RELEASE = \"$escaped_release\";"
} > "$temporary_file"

# Preserve the existing file timestamp when its contents have not changed.
if [ -f "$output_file" ] && cmp -s "$temporary_file" "$output_file"; then
    rm -f "$temporary_file"
else
    mv "$temporary_file" "$output_file"
fi

trap - EXIT HUP INT TERM
printf 'Generated %s: %s\n' "$output_file" "$release"
