#! /bin/sh -x

YAHRZEIT=/Users/allan/Sites/yahrzeit

cat > /tmp/$$ << _EOF_
    
re
re
all off

all on 1

all on 2

all on 3

all on 4

all on 5

all on 6

all on 7

all on 9

all on 10

all on 13

all on 16

all on 19

re
re

_EOF_

$YAHRZEIT/bin/yahr_conduit -i /tmp/$$ -n 192.168.2.9 -p 2001
